[package]
name = "del-fem"
version = "0.1.3"
edition = "2021"
description = "finite element method (FEM) utility codes"
documentation = "https://docs.rs/del_fem"
repository = "https://github.com/nobuyuki83/del-fem/"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.19"
nalgebra = "0.32.6"
itertools = "0.13.0"

del-geo = {path="../del-geo"}
del-msh = {path="../del-msh"}