[package]
name = "del-fem"
version = "0.1.0"
edition = "2021"
description = "finite element method (FEM) utility codes"
documentation = "https://docs.rs/del_fem"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.18"
nalgebra = "0.32.3"
# del-geo = {path="../del-geo"}
del-geo = "0.1.18"